name: Doc Generation
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build HTML documentation
        run: |
          sphinx-apidoc -o docs/source/ sample/ || { echo "sphinx-apidoc command failed"; exit 1; }
          cd docs
          make html || { echo "Sphinx documentation build failed"; exit 1; }
      - name: Archive HTML documentation
        run: |
          cd source/build/html
          zip -r ../../../api_docs.zip . || { echo "Zipping documentation failed"; exit 1; }
      - name: Upload html documentation
        uses: actions/upload-artifact@v2
        with:
          name: sphinx-docs
          path: api_docs.zip